### ISSUE TITLE
Question about the frequency of updating momentum network

### ISSUE THREAD

**Issue by super233** [visinf/da-sac#2]
Thanks for sharing the code.

Have you investigate the influence of _**T**_ (frequency of updating momentum network)? There's not corresponding ablation study in paper.

Counld you please report the result of setting with different  **_T_** ?

**Comment by arnike** [comment]
Hi @super233,

we did not run an exhausitive sensitivity analysis of our model, but only a selected few which were of concern due to computational constraints. With regard to `T`, we only looked into the extreme setting without the momentum net (T = 1, \gamma_\psi = 0).
However, it is straightforward to modify `T` in the code (relevant settings are `MODEL.NET_MOMENTUM_ITER` and `MODEL.NET_MOMENTUM`), if your use case requires a more detailed study.

Best,
Nikita

**Comment by super233** [comment]
Thanks, I got it.
