### ISSUE TITLE
How do you think whether the knowledge distillation can bring improvement for UDA?

### ISSUE THREAD

**Issue by super233** [visinf/da-sac#3]
How do you think about the  "**4.3. Distillation to self-supervised model**" in [ProDA](http://arxiv.org/abs/2101.10979)? 
**The ProDA without knowledge distillation has a result similar to SAC**, and how do you think whether knowledge distillation can bring enhancement for SAC?

![image](https://user-images.githubusercontent.com/35358984/122660868-765da100-d1b7-11eb-97c1-a3327c809171.png)

**Comment by arnike** [comment]
Hi @super233 ,

this is an interesting question. Training on "cleaner" pseudo labels in multiple rounds usually improves the baseline accuracy, so I'd expect this to apply to SAC as well.
However, there might be easier ways of improving the accuracy of SAC if you have the computation budget of ProDA, such as increasing the number of augmentations per image (for better calibration), the number of different images in the batch (for improved stability), or simply using higher resolution (for improved accuracy of long-tail classes).
On a sidenote, SAC and ProDA are not head-to-head comparable, since ProDA uses a different "warm-up" model (based on adversarial feature alignment) and a modified ASPP architecture.

Hope this helps,
Nikita

**Comment by super233** [comment]
I can't agree with you more. Thanks for sharing your points! 😄
