### ISSUE TITLE
How to evaluate model without using cityscapes scripts protocol

### ISSUE THREAD

**Issue by fabriziojpiva** [visinf/da-sac#6]
Hi, thanks for your contribution! I really like your paper. I am currently training your model in a slightly different setup (Cityscapes ---> BDD), and I see that your algorithm is already able to run an evaluation on all the validation dataloaders defined in `datasets/__init__.py` after finishing every epoch. 

What I would like to do is to actually evaluate the resulting model on other datasets that do not participate in the training process. In order to do this, I am forced to load your model and checkpoint, and run an evaluation on the datasets that I want. Aside from generating the `.txt` files on the `data` folder, how can I run the evaluation without having to use the scripts of cityscapes?

**Comment by arnike** [comment]
Hi, you need to modify [the function returning the validation lists](https://github.com/visinf/da-sac/blob/f18691f3ffeebea1d9e0112b0a5c24a66f5bf5a0/datasets/__init__.py#L21). Note that the validation IoU reported at training time will not match that of the final inference process (due to [the centre cropping and re-scaling](https://github.com/visinf/da-sac/blob/f18691f3ffeebea1d9e0112b0a5c24a66f5bf5a0/datasets/dataloader_seg.py#L87)).
